version: 2
updates:
  # - package-ecosystem: npm
  #   directory: /
  #   schedule:
  #     interval: weekly
  #   open-pull-requests-limit: 10
  #   groups:
  #     aws-sdk:
  #       patterns:
  #         - "@aws-sdk/*"
  #     dev-deps:
  #       patterns:
  #         - "@types/*"
  #         - "ts-jest"
  #         - "typescript"
  #         - "esbuild"
  #         - "ts-node"
  #         - "jest"
  #         - "aws-sdk-client-mock"

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
