spring.application.name=digest

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/digest
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Determines how the schema is created or updated, turn off in prod
spring.jpa.hibernate.ddl-auto=update

# Shows SQL statement in console, might turn off later
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keys
newsapi.key=${NEWSAPI_KEY}
newsapi.base-url=https://newsapi.org/v2/top-headlines